import { NextRequest, NextResponse } from "next/server";
import type { AnalysisResult } from "@/app/types/analysis";

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/parse-report
//
// Accepts: multipart/form-data with field "file" (PDF, PNG, JPG)
//          and optional field "fileType" ("uniquely-us" | "clinical" | "other")
//
// Returns: { source, parsedResult: AnalysisResult, rawText?, insights }
//
// HOW TO CONNECT YOUR REAL DOCUMENT PARSER:
//   Find the block marked "YOUR PARSER CODE GOES HERE" below.
//   Replace the mock with your actual OCR / PDF text-extraction logic.
//   Good options:
//     - pdf-parse (npm) for text extraction from PDFs
//     - Google Document AI or Azure Form Recognizer for clinical docs
//     - Tesseract.js for image OCR
// ─────────────────────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  try {
    const formData = await req.formData();
    const file = formData.get("file") as File | null;
    const fileType = (formData.get("fileType") as string) ?? "clinical";

    if (!file) {
      return NextResponse.json({ error: "No file provided." }, { status: 400 });
    }

    const fileName = file.name.toLowerCase();
    const fileSize = file.size;

    // ─── YOUR PARSER CODE GOES HERE ─────────────────────────────────────────
    //
    // Step 1 — Extract text / data from the file:
    //
    // Option A — pdf-parse for Uniquely Us PDFs:
    //   import pdfParse from "pdf-parse";
    //   const buffer = Buffer.from(await file.arrayBuffer());
    //   const pdfData = await pdfParse(buffer);
    //   const text = pdfData.text;
    //   const metadata = pdfData.info; // check for uniquely-us-report keyword
    //
    // Option B — Google Document AI for clinical PDFs:
    //   const { DocumentProcessorServiceClient } = await import("@google-cloud/documentai");
    //   const client = new DocumentProcessorServiceClient();
    //   const [result] = await client.processDocument({ ... });
    //   const text = result.document.text;
    //
    // Option C — Tesseract.js for image files (PNG/JPG):
    //   const { createWorker } = await import("tesseract.js");
    //   const worker = await createWorker("eng");
    //   const { data: { text } } = await worker.recognize(buffer);
    //
    // Step 2 — Run your classification model on the extracted text:
    //   const classifierResult = await yourClassifier(text);
    //
    // Step 3 — Build and return AnalysisResult from classifierResult.
    //
    const parsedResult = runMockParser(fileName, fileSize, fileType);
    // ─── END PARSER BLOCK ────────────────────────────────────────────────────

    return NextResponse.json({
      source: fileType === "uniquely-us" ? "Uniquely Us Report Re-imported" : "Clinical Report Analysed",
      fileName: file.name,
      fileSize,
      parsedResult,
    }, { status: 200 });

  } catch (err) {
    console.error("[ParseReportRoute] Error:", err);
    return NextResponse.json({ error: "Failed to parse report." }, { status: 500 });
  }
}

// ─── MOCK PARSER (delete when your real parser is connected) ─────────────────
function runMockParser(fileName: string, fileSize: number, fileType: string): AnalysisResult {
  // Determine a mock score based on file characteristics (purely demo)
  const sizeScore = Math.min(100, Math.round((fileSize / 50000) * 50 + 30));
  const isOwnReport = fileName.includes("uniquelyus") || fileType === "uniquely-us";

  const score = isOwnReport ? 52 : sizeScore;
  const riskLevel = score >= 70 ? "High" : score >= 40 ? "Moderate" : "Low";
  const asdLevel =
    score >= 75 ? "Level 3 — Requiring Very Substantial Support"
    : score >= 50 ? "Level 2 — Requiring Substantial Support"
    : score >= 30 ? "Level 1 — Requiring Support"
    : "Sub-threshold — No ASD Indicated";

  return {
    modelId: "behavioral",
    modelName: isOwnReport ? "Uniquely Us Re-import" : "Clinical Report Parser",
    timestamp: new Date().toISOString(),
    riskLevel,
    asdLevel,
    overallScore: score,
    confidence: isOwnReport ? 95 : 68,
    summary: isOwnReport
      ? "This report was previously generated by the Uniquely Us platform and has been successfully re-imported. The original assessment data has been restored and is displayed below."
      : `Clinical report analysed using AI-assisted document parsing. The document (${fileName}) contained indicators consistent with ${asdLevel}. For highest accuracy, ensure the report is a clear, machine-readable PDF from a recognised assessment provider.`,
    findings: [
      { label: "Social Communication",    score: Math.round(score * 0.95), comment: "Extracted from report — social communication domain indicators." },
      { label: "Restricted Behaviors",   score: Math.round(score * 1.05), comment: "Repetitive and restricted behavior markers identified in document." },
      { label: "Sensory Profile",         score: Math.round(score * 0.9),  comment: "Sensory sensitivity indicators referenced in clinical notes." },
      { label: "Adaptive Functioning",    score: Math.round(score * 0.85), comment: "Daily living and independence assessment markers extracted." },
    ],
    interventions: [
      { type: "Applied Behavior Analysis (ABA)",  description: "Recommended based on detected behavioral profile severity.",      priority: "High"   },
      { type: "Speech-Language Therapy",          description: "Communication indicators suggest SLT would be beneficial.",        priority: "High"   },
      { type: "Occupational Therapy",             description: "Sensory and adaptive functioning suggest OT referral.",            priority: "Medium" },
      { type: "Parental Guidance Program",        description: "Family-centered support strategies aligned with report findings.", priority: "Medium" },
    ],
    nextSteps: [
      { order: 1, action: "Share with developmental pediatrician",  detail: "Present this imported report at your next specialist appointment." },
      { order: 2, action: "Begin recommended therapy programme",    detail: "Contact an ABA or SLT provider as per the interventions above." },
      { order: 3, action: "Run a platform assessment",              detail: "Take one of our 3 AI model tests to cross-validate these results." },
    ],
    disclaimer: "This analysis was generated from an uploaded document using AI-assisted parsing. Accuracy depends on the quality and format of the source document. This is not a clinical diagnosis.",
  };
}
